### ISSUE TITLE
Android doesn't register device tokens

### ISSUE THREAD

**Issue by khactam** [taivo/parse-push-plugin#119]
Im using the version 1.0.8 and device register a new Installation object fine but there is not device token has been saved in the object. The version 1.0.7 works fine but not the 1.0.8. What I want to use the version 1.0.8 is the silent notification (when I use 1.0.7, android gets the empty notification)

![screen shot 2018-05-15 at 13 01 11](https://user-images.githubusercontent.com/15610040/40050450-30703cdc-5840-11e8-8705-3e550a6a9ee8.png)

ionic: 3.20.0
cordova: 8.0.0

I use parse-server and it works fine until now.

My implement: 

app.js
```
if(window.ParsePushPlugin){
      ParsePushPlugin.getInstallationId(function(id) {
          console.log("device installationId: " + id);
      }, function(e) {
          alert('error');
      });
}
```
config.xml
```
<preference name="ParseAppId" value="gijfdguo........." />
<preference name="ParseServerUrl" value="http://......../parse/" />
<preference name="ParseGcmSenderId" value="1........" />
```

**Comment by khactam** [comment]
```
05-15 17:50:20.381 1169-13676/? I/ChromeSync: [Sync,SyncIntentOperation] Handling the intent: Intent { act=com.google.android.gms.chromesync.SCHEDULED_SYNC cat=[targeted_intent_op_prefix:.chromesync.sync.SyncIntentOperation] dat=content://com.google.android.gms.chromesync.sync.ChimeraSyncReceiverService/109125016589231836921 flg=0x4 cmp=com.google.android.gms/.chimera.GmsIntentOperationService launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } (has extras) }.
05-15 17:50:20.502 4333-4365/? E/Auth: [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:1264340651>, App: com.google.android.gms, Service: oauth2:https://www.googleapis.com/auth/login_manager
    fzk: Long live credential not available.
        at fzl.b(:com.google.android.gms@12673021@12.6.73 (040306-194189626):20)
        at fzl.a(:com.google.android.gms@12673021@12.6.73 (040306-194189626):50)
        at fxv.a(:com.google.android.gms@12673021@12.6.73 (040306-194189626):38)
        at hox.a(:com.google.android.gms@12673021@12.6.73 (040306-194189626):8)
        at hox.a(:com.google.android.gms@12673021@12.6.73 (040306-194189626):189)
        at hnx.a(:com.google.android.gms@12673021@12.6.73 (040306-194189626):2)
        at hnu.a(:com.google.android.gms@12673021@12.6.73 (040306-194189626):17)
        at hnu.a(:com.google.android.gms@12673021@12.6.73 (040306-194189626):6)
        at cyb.a(:com.google.android.gms@12673021@12.6.73 (040306-194189626):25)
        at cyb.a(:com.google.android.gms@12673021@12.6.73 (040306-194189626):82)
        at cyb.onTransact(:com.google.android.gms@12673021@12.6.73 (040306-194189626):8)
        at android.os.Binder.transact(Binder.java:507)
        at dah.onTransact(:com.google.android.gms@12673021@12.6.73 (040306-194189626):3)
        at android.os.Binder.execTransact(Binder.java:573)
05-15 17:50:20.502 4333-4365/? W/Auth: [GetToken] GetToken failed with status code: BadAuthentication
```

Not pretty sure if this could be useful

**Comment by khactam** [comment]
I thought it was about the legacy key but it's not, when I changed to the long API key still got the same outcome. And btw what PR you mean?

**Comment by taivo** [comment]
@khactam thanks for figuring out the problem. Could you help by submitting a pull request?

**Comment by saisreeharsha** [comment]
> I found the problem. It's here in the afterAndroidPrepare.js.
> 
> ```
>  var parsePushNotificationIcon = configXml.data.find('preference[@name="ParseNotificationIcon"]').get('value');
>   if (!!parsePushNotificationIcon) {
>     // add to AndroidManifest.xml
>     var manifestPushNotificationIconNode = applicationNode.find('meta-data[@android:name="com.parse.push.notification_icon"]');
> 
>     if (!manifestPushNotificationIconNode) {
>       manifestPushNotificationIconNode = new ET.Element('meta-data', { 'android:name': 'com.parse.push.notification_icon' });
>       applicationNode.append(manifestPushNotificationIconNode);
>     }
>     manifestPushNotificationIconNode.set('android:resource', '@drawable/' + parsePushNotificationIcon);
> 
>     // COPY ICON
>     // create target path
>     var iconTargetPath = path.join(context.opts.projectRoot, 'platforms', 'android', 'res', 'drawable');
>     try {
>       fs.mkdirSync(iconTargetPath);
>     } catch (err) {
>       // Directory already exists
>     }
> 
>     // copy icon to android folder
>     fs
>       .createReadStream(path.join(context.opts.projectRoot, 'resources', parsePushNotificationIcon + '.png'))
>       .pipe(fs.createWriteStream(path.join(iconTargetPath, parsePushNotificationIcon + '.png')));
>   }
> ```
> Just after I remove this (because I dont have the icon so it cant prepare perfectly. I put 1 condition there and everything is fine.

Where do i find this file named "afterAndroidPrepare.js"

**Comment by budda** [comment]
> afterAndroidPrepare.js



> @khactam Where do i find this file named "afterAndroidPrepare.js" ???

It's in the scripts folder

https://github.com/taivo/parse-push-plugin/blob/5b616c0ce2993a7104fee7833481b91102695b12/scripts/afterAndroidPrepare.js#L15
