### ISSUE TITLE
Installation error: cannot find module "cordova-common"

### ISSUE THREAD

**Issue by pablo-gonzalez** [taivo/parse-push-plugin#46]
Hi

I have used the previous version of the plugin sucessfully.
Now I am tryting to test the lastest version but I got an error during installation.

Thanks in advance.
Pablo

```
C:\Users\Pablo\Documents\projects\new_push>cordova plugin add https://github.com/taivo/parse-push-plugin
Fetching plugin "https://github.com/taivo/parse-push-plugin" via git clone
Repository "https://github.com/taivo/parse-push-plugin" checked out to git ref "master".
Installing "parse-push-plugin" for android
Failed to install 'parse-push-plugin':Error: Cannot find module 'cordova-common'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Context.requireCordovaModule (C:\Users\Pablo\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\Context.js:48:12)
    at module.exports (C:\Users\Pablo\Documents\projects\new_push\plugins\parse-push-plugin\scripts\beforeAndroidInstall.js:10:29)
    at runScriptViaModuleLoader (C:\Users\Pablo\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:152:18)
    at runScript (C:\Users\Pablo\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:130:16)
    at C:\Users\Pablo\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:115:20
    at _fulfilled (C:\Users\Pablo\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
Error: Cannot find module 'cordova-common'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Context.requireCordovaModule (C:\Users\Pablo\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\Context.js:48:12)
    at module.exports (C:\Users\Pablo\Documents\projects\new_push\plugins\parse-push-plugin\scripts\beforeAndroidInstall.js:10:29)
    at runScriptViaModuleLoader (C:\Users\Pablo\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:152:18)
    at runScript (C:\Users\Pablo\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:130:16)
    at C:\Users\Pablo\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:115:20
    at _fulfilled (C:\Users\Pablo\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)

C:\Users\Pablo\Documents\projects\new_push>ionic info

Your system information:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Version: 1.3.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 8
Node Version: v0.12.2

```

**Comment by taivo** [comment]
Hi Pablo,
The new hook scripts I added to simplify installation uses `cordova-common`. An update of your cordova would easily fix the issue. See [http://stackoverflow.com/questions/34076616/i-am-getting-error-error-cannot-find-module-cordova-common-when-installing](http://stackoverflow.com/questions/34076616/i-am-getting-error-error-cannot-find-module-cordova-common-when-installing)

**Comment by pablo-gonzalez** [comment]
Thank you very much. After updating cordova and cordova-android it worked.
